CATEGORIES = [
    {"id": "science",  "label": "Science",      "icon": "🔬"},
    {"id": "history",  "label": "History",       "icon": "🏛️"},
    {"id": "tech",     "label": "Tech",          "icon": "💻"},
    {"id": "sports",   "label": "Sports",        "icon": "⚽"},
    {"id": "geo",      "label": "Geography",     "icon": "🌍"},
    {"id": "pop",      "label": "Pop Culture",   "icon": "🎬"},
]

QUESTIONS = {
    "science": [
        {"q": "What is the chemical symbol for Gold?", "options": ["Au", "Ag", "Gd", "Go"], "answer": 0},
        {"q": "How many bones are in the adult human body?", "options": ["196", "206", "216", "186"], "answer": 1},
        {"q": "What planet is known as the Red Planet?", "options": ["Venus", "Jupiter", "Mars", "Saturn"], "answer": 2},
        {"q": "What gas do plants absorb from the atmosphere?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": 2},
        {"q": "What is the speed of light (approx)?", "options": ["300,000 km/s", "150,000 km/s", "450,000 km/s", "200,000 km/s"], "answer": 0},
        {"q": "What is the powerhouse of the cell?", "options": ["Nucleus", "Ribosome", "Mitochondria", "Lysosome"], "answer": 2},
        {"q": "What is H₂O commonly known as?", "options": ["Hydrogen", "Water", "Oxygen", "Salt"], "answer": 1},
        {"q": "How many elements are on the periodic table?", "options": ["108", "112", "118", "126"], "answer": 2},
        {"q": "What force keeps planets in orbit?", "options": ["Magnetism", "Gravity", "Friction", "Inertia"], "answer": 1},
        {"q": "Most abundant gas in Earth's atmosphere?", "options": ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], "answer": 2},
    ],
    "history": [
        {"q": "In which year did World War II end?", "options": ["1943", "1944", "1945", "1946"], "answer": 2},
        {"q": "Who was the first President of the United States?", "options": ["John Adams", "Thomas Jefferson", "Benjamin Franklin", "George Washington"], "answer": 3},
        {"q": "The Berlin Wall fell in which year?", "options": ["1987", "1988", "1989", "1991"], "answer": 2},
        {"q": "Which civilization built Machu Picchu?", "options": ["Aztec", "Maya", "Inca", "Olmec"], "answer": 2},
        {"q": "In which year did India gain independence?", "options": ["1945", "1947", "1948", "1950"], "answer": 1},
        {"q": "Who painted the Sistine Chapel ceiling?", "options": ["Da Vinci", "Raphael", "Donatello", "Michelangelo"], "answer": 3},
        {"q": "The French Revolution began in which year?", "options": ["1776", "1789", "1799", "1804"], "answer": 1},
        {"q": "Which empire was ruled by Julius Caesar?", "options": ["Greek", "Ottoman", "Roman", "Byzantine"], "answer": 2},
        {"q": "Who wrote the 'I Have a Dream' speech?", "options": ["Malcolm X", "Barack Obama", "MLK Jr.", "Frederick Douglass"], "answer": 2},
        {"q": "The Titanic sank in which year?", "options": ["1910", "1911", "1912", "1914"], "answer": 2},
    ],
    "tech": [
        {"q": "Who co-founded Apple with Steve Jobs?", "options": ["Bill Gates", "Steve Wozniak", "Paul Allen", "Jony Ive"], "answer": 1},
        {"q": "What does 'HTTP' stand for?", "options": ["HyperText Transfer Protocol", "High Text Tech Process", "Hyper Transfer Text Page", "Host Text Transfer Protocol"], "answer": 0},
        {"q": "Which year was the first iPhone released?", "options": ["2005", "2006", "2007", "2008"], "answer": 2},
        {"q": "What does CPU stand for?", "options": ["Central Processing Unit", "Core Power Unit", "Central Program Utility", "Computer Power Unit"], "answer": 0},
        {"q": "Binary representation of the number 10?", "options": ["0110", "1010", "1100", "1001"], "answer": 1},
        {"q": "Which company owns YouTube?", "options": ["Meta", "Microsoft", "Amazon", "Google"], "answer": 3},
        {"q": "Best language for AI/ML?", "options": ["Java", "C++", "Python", "JavaScript"], "answer": 2},
        {"q": "What does 'RAM' stand for?", "options": ["Random Access Memory", "Read And Modify", "Run And Manage", "Rapid Access Module"], "answer": 0},
        {"q": "Who is the CEO of Tesla?", "options": ["Jeff Bezos", "Elon Musk", "Tim Cook", "Sundar Pichai"], "answer": 1},
        {"q": "What does 'SQL' stand for?", "options": ["Structured Query Language", "Simple Query Logic", "System Query Layer", "Sequential Query List"], "answer": 0},
    ],
    "sports": [
        {"q": "Players on a standard football (soccer) team?", "options": ["9", "10", "11", "12"], "answer": 2},
        {"q": "Where did the Olympic Games originate?", "options": ["Italy", "Egypt", "Greece", "Turkey"], "answer": 2},
        {"q": "How many Grand Slam tournaments in tennis?", "options": ["2", "3", "4", "5"], "answer": 2},
        {"q": "What sport uses a puck?", "options": ["Field Hockey", "Ice Hockey", "Lacrosse", "Polo"], "answer": 1},
        {"q": "Most Olympic gold medals holder?", "options": ["Usain Bolt", "Michael Phelps", "Carl Lewis", "Mark Spitz"], "answer": 1},
        {"q": "Points for a basketball three-pointer?", "options": ["1", "2", "3", "4"], "answer": 2},
        {"q": "FIFA World Cup held every how many years?", "options": ["2", "3", "4", "5"], "answer": 2},
        {"q": "Which country invented cricket?", "options": ["Australia", "India", "England", "South Africa"], "answer": 2},
        {"q": "How long is a standard marathon?", "options": ["40 km", "42.195 km", "45 km", "38 km"], "answer": 1},
        {"q": "In which sport can you score an 'eagle'?", "options": ["Archery", "Golf", "Badminton", "Tennis"], "answer": 1},
    ],
    "geo": [
        {"q": "What is the capital city of Australia?", "options": ["Sydney", "Melbourne", "Brisbane", "Canberra"], "answer": 3},
        {"q": "Which is the longest river in the world?", "options": ["Amazon", "Nile", "Yangtze", "Mississippi"], "answer": 1},
        {"q": "How many continents are there?", "options": ["5", "6", "7", "8"], "answer": 2},
        {"q": "Which country has the most natural lakes?", "options": ["Russia", "USA", "Brazil", "Canada"], "answer": 3},
        {"q": "Mount Everest is in which mountain range?", "options": ["Andes", "Alps", "Himalayas", "Rockies"], "answer": 2},
        {"q": "Smallest country in the world?", "options": ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], "answer": 2},
        {"q": "Which ocean is the largest?", "options": ["Atlantic", "Indian", "Arctic", "Pacific"], "answer": 3},
        {"q": "What is the capital of Japan?", "options": ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], "answer": 2},
        {"q": "Amazon Rainforest primarily in which country?", "options": ["Colombia", "Peru", "Brazil", "Venezuela"], "answer": 2},
        {"q": "Largest population in Africa?", "options": ["Ethiopia", "Egypt", "Nigeria", "South Africa"], "answer": 2},
    ],
    "pop": [
        {"q": "Who played Iron Man in the MCU?", "options": ["Chris Evans", "Robert Downey Jr.", "Mark Ruffalo", "Chris Pratt"], "answer": 1},
        {"q": "Which band wrote 'Bohemian Rhapsody'?", "options": ["The Beatles", "Led Zeppelin", "Queen", "The Rolling Stones"], "answer": 2},
        {"q": "In Breaking Bad, Walter White's alias?", "options": ["El Chapo", "Heisenberg", "The Cook", "Scarface"], "answer": 1},
        {"q": "Which game features Master Chief?", "options": ["Gears of War", "Call of Duty", "Halo", "Destiny"], "answer": 2},
        {"q": "Best-selling video game of all time?", "options": ["GTA V", "Minecraft", "Tetris", "Wii Sports"], "answer": 1},
        {"q": "Who sang 'Thriller'?", "options": ["Prince", "Michael Jackson", "David Bowie", "Elton John"], "answer": 1},
        {"q": "In which city does Batman live?", "options": ["Metropolis", "Star City", "Central City", "Gotham City"], "answer": 3},
        {"q": "Which service produced 'Stranger Things'?", "options": ["HBO", "Disney+", "Netflix", "Amazon Prime"], "answer": 2},
        {"q": "Highest-grossing film of all time?", "options": ["Avengers: Endgame", "Titanic", "Avatar", "Star Wars: TFA"], "answer": 2},
        {"q": "Who sang 'Shape of You'?", "options": ["Justin Bieber", "Ed Sheeran", "Harry Styles", "Bruno Mars"], "answer": 1},
    ],
}
